INSERT INTO `addresbook` (`id`, `name`, `firstName`, `city`, `street`, `zipCode`, `deleted`) VALUES
(1, 'Armen', 'Grigoryan', 1, 'Vardanants 4', '0056', 0),
(2, 'testNmae', 'test latNmae', 2, 'tastAddress', '0056', 0),
(3, 'Artur', 'Harutunyan', 3, 'Shiraki 13, 35', '0065', 0),
(4, 'harutunyan', 'Artur', 4, 'Shiraki 13, 35', '0055', 0);
INSERT INTO `cities` (`id`, `name`) VALUES
(1, 'Schaffhausen'),
(2, 'Aargau'),
(3, 'Glarus'),
(4, 'Zürich'),
(5, 'Jura'),
(6, 'Basel-Landschaft'),
(7, 'Basel-Stadt'),
(8, 'Solothurn'),
(9, 'Fribourg'),
(10, 'Zug'),
(11, 'Graubünden'),
(12, 'Obwalden'),
(13, 'Schwyz'),
(14, 'Luzern'),
(15, 'Neuchâtel'),
(16, 'Uri'),
(17, 'Bern'),
(18, 'Genève'),
(19, 'Vaud'),
(20, 'Bern'),
(21, 'Nidwalden'),
(22, 'Sankt Gallen'),
(23, 'Appenzell Innerrhoden'),
(24, 'Appenzell Ausserrhoden'),
(25, 'Thurgau'),
(26, 'Ticino'),
(27, 'Ticino'),
(28, 'Valais'),
(29, 'Schaffhausen'),
(30, 'Aargau'),
(31, 'Jura'),
(32, 'Solothurn');
